source :rubygems
gem 'sinatra', '>= 1.0'
gem 'debugger'
gem 'sinatra-contrib'
gem 'rake'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'dm-do-adapter'
gem 'slim'
gem 'thin'
gem 'addressable'
